// Runtime guards must use the same enum values as the introspected schema.
module.exports.plugin = (schema) => ({
  prepend: ['// Generated by npm run graphql:generate. Do not edit.'],
  content: ['CountriesEnum', 'ProductTaxonomyEnum'].map(name => {
  const type = schema.getType(name);
  if (!type || typeof type.getValues !== 'function') throw new Error(`Missing enum ${name}`);
  return `export const ${name}Values = ${JSON.stringify(type.getValues().map(value => value.name))} as const;`;
  }).join('\n'),
});
